#!/usr/bin/env bash

# Esegui una scansione Wi-Fi aggiornata
nmcli device wifi rescan &>/dev/null
sleep 2

# Ottieni lista reti ordinate per segnale
networks=$(nmcli -t -f SSID,SIGNAL device wifi list | grep -v "^:" | awk -F: '$1 != "" {print $1 "\t" $2}' | sort -k2 -nr | awk -F'\t' '!seen[$1]++ {printf "(%s%%) %s\n", $2, $1}')

# Mostra la lista con rofi
choice=$(echo -e "$networks\n--------------------\nBack\nExit" | rofi -dmenu -i -p "Selezione rete")

# Gestione scelte
case "$choice" in
    "("*)
        # Estrai il nome della rete
        ssid=$(echo "$choice" | sed -E 's/^\([0-9]+%\) //')

        # Se è già configurata, connettiti direttamente
        if nmcli connection show | grep -qw "$ssid"; then
            nmcli connection up "$ssid"
            $HOME/.config/rofi/Network/rofi-network
        else
            if [[ -z "$security" || "$security" == "--" ]]; then
                # Rete aperta, nessuna password richiesta
                nmcli device wifi connect "$ssid"
            else
                # Rete protetta, richiedi la password
                password=$(rofi -dmenu -p "Password per $ssid:" -password)
                [[ -z "$password" ]] && exit 1
                nmcli device wifi connect "$ssid" password "$password"
            fi
            $HOME/.config/rofi/Network/rofi-network
        fi
        ;;
    "Back")
        $HOME/.config/rofi/Network/rofi-network
        ;;
    *)
        exit 0
        ;;
esac
