#!/bin/bash

# Funzione per ottenere luminosità corrente
get_brightness() {
    # Ottieni luminosità corrente e massima
    current=$(brightnessctl get)
    max=$(brightnessctl max)

    # Calcola percentuale
    percent=$(( (current / 6000)*10 ))

    filled_blocks=$((percent / 10))
    empty_blocks=$((10 - filled_blocks))

    bar=""
    for ((i=0; i<filled_blocks; i++)); do
        bar+="#"
    done
    for ((i=0; i<empty_blocks; i++)); do
        bar+="_"
    done

    echo "$percent% [$bar]"
}

# Funzione per controllare se wlsunset è attivo
is_night_light_on() {
    if pgrep -x "wlsunset" > /dev/null; then
        echo "on"
    else
        echo "off"
    fi
}

# Loop principale
while true; do
    current_brightness=$(get_brightness)
    night_light_status=$(is_night_light_on)

    # Menu Rofi
    choice=$(echo -e "Luminosità: $current_brightness\nLuce notturna: $night_light_status\n--------------------\nBrightness-up: +10%\nBrightness-down: -10%\n--------------------\nExit" | rofi -dmenu -i -p "Gestione Luminosità")

    case "$choice" in
        "Brightness-up: +10%")
            brightnessctl set +10%
            ;;
        "Brightness-down: -10%")
            brightnessctl set 10%-
            ;;
        "Luce notturna: $night_light_status")
            if pgrep -x "wlsunset" > /dev/null; then
                pkill "wlsunset"
            else
                # Trick ammetto molto brutto ma funzionante per poter avere una luce notturna che si attiva quando si vuole
                wlsunset -t 3999 -T 4000 -d 0 -S 08:00 -s 17:59 > /dev/null 2>&1 &
            fi
            ;;
        *)
            exit 0
            ;;
    esac
done