#!/bin/bash

# Funzione per ottenere luminosità corrente
get_brightness() {
    # Ottieni luminosità corrente e massima
    current=$(brightnessctl get)
    max=$(brightnessctl max)

    # Calcola percentuale
    percent=$(( (current / 6000)*10 ))

    filled_blocks=$((percent / 10))
    empty_blocks=$((10 - filled_blocks))

    bar=""
    for ((i=0; i<filled_blocks; i++)); do
        bar+="#"
    done
    for ((i=0; i<empty_blocks; i++)); do
        bar+="_"
    done

    echo "$percent% [$bar]"
}

# Loop principale
while true; do
    current_brightness=$(get_brightness)

    # Menu Rofi
    choice=$(echo -e "Luminosità: $current_brightness\n---------\nBrightness-up: +10%\nBrightness-down: -10%\n----------\nExit" | rofi -dmenu -i -p "Gestione Luminosità")

    case "$choice" in
        "Brightness-up: +10%")
            brightnessctl set +10%
            ;;
        "Brightness-down: -10%")
            brightnessctl set 10%-
            ;;
        *)
            exit 0
            ;;
    esac
done